### ISSUE TITLE
Cannot connect to host speech.platform.bing.com:443 ssl:default

### ISSUE THREAD

**Issue by dpengchen** [rany2/edge-tts#113]
error ⬇️ 
```shell
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/concurrent/futures/_base.py", line 438, in result
return self.__get_result()
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
raise self._exception
File "/www/wwwroot/python-project/edge-tts/app.py", line 70, in voices
list = await edge_tts.list_voices()
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/edge_tts/list_voices.py", line 24, in list_voices
async with session.get(
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
self._resp = await self._coro
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
conn = await self._connector.connect(
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
proto = await self._create_connection(req, traces, timeout)
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/www/server/pyporject_evn/4a76ad6e51b2a2c985e8bd15df2c400a_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:default [Connect call failed ('2620:1ec:c11::237', 443, 0, 0)]
```

**Comment by dpengchen** [comment]
```shell
Cannot connect to host speech.platform.bing.com:443 ssl:defaut
```

What kind of question is that

**Comment by dpengchen** [comment]
I solved the problem.The reason is the Python version, if your version is also 3.10, it is recommended to switch to 3.8 or other versions
