### ISSUE TITLE
aiohttp.client_exceptions.WSServerHandshakeError: 503, message='Invalid response status', 

### ISSUE THREAD

**Issue by tiandaye** [rany2/edge-tts#180]
```
Traceback (most recent call last):
  File "/projects/python_projects/pachong/video/edge-tts-demo/learn1.py", line 25, in <module>
    asyncio.run(_main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/projects/python_projects/pachong/video/edge-tts-demo/learn1.py", line 21, in _main
    await communicate.save(OUTPUT_FILE)
  File "/projects/python_projects/pachong/venv/lib/python3.11/site-packages/edge_tts/communicate.py", line 459, in save
    async for message in self.stream():
  File "/projects/python_projects/pachong/venv/lib/python3.11/site-packages/edge_tts/communicate.py", line 306, in stream
    async with aiohttp.ClientSession(
  File "/projects/python_projects/pachong/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/projects/python_projects/pachong/venv/lib/python3.11/site-packages/aiohttp/client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 503, message='Invalid response status', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=681699ba0df346eaa1264f0d2845c8b1')
```

**Comment by hellojet** [comment]
+1

**Comment by rany2** [comment]
Can't reproduce, might be a temporary server-side issue.

**Comment by tiandaye** [comment]
> Can't reproduce, might be a temporary server-side issue.

Thank you! It's working now.
