### ISSUE TITLE
Is it possible to run when only one thread?

### ISSUE THREAD

**Issue by wa008** [rany2/edge-tts#243]
I want to run this project on web though pyodide. When I run the same code which works in my local computer on web, I get this error

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 522, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/_pyodide/_base.py", line 356, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 9, in <module>
  File "/lib/python3.12/site-packages/edge_tts/communicate.py", line 550, in stream_sync
    executor.submit(fetch_async_items, queue)
  File "/lib/python312.zip/concurrent/futures/thread.py", line 179, in submit
    self._adjust_thread_count()
  File "/lib/python312.zip/concurrent/futures/thread.py", line 202, in _adjust_thread_count
    t.start()
  File "/lib/python312.zip/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

code:
```
            import edge_tts
            import asyncio
            # import numpy
            import sys
            print (sys.platform, 'debug')
            communicate = edge_tts.Communicate('${TEXT}', '${VOICE}')
            output = b''
            for chunk in communicate.stream_sync():
                if chunk["type"] == "audio":
                    output += chunk["data"]
                    print (type(chunk["data"]))
                elif chunk["type"] == "WordBoundary":
                    print(f"WordBoundary: {chunk}")
```

I guess that is becuase js only have on thread, so, I want to know Is it possible to run this project when only one thread?

**Comment by rany2** [comment]
Just use the async variant of the function.

**Comment by wa008** [comment]
It also doesn't work if I use async variant. it seems the environment issues.

code:
```
            import edge_tts
            import asyncio
            # import numpy
            import sys
            print (sys.platform, 'debug')
            communicate = edge_tts.Communicate('${TEXT}', '${VOICE}')
            output = b''
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    output += chunk["data"]
                    print (type(chunk["data"]))
                elif chunk["type"] == "WordBoundary":
                    print(f"WordBoundary: {chunk}")
            output
```

error:
```
pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 412, in run_async
    await coroutine
  File "<exec>", line 9, in <module>
  File "/lib/python3.12/site-packages/edge_tts/communicate.py", line 506, in stream
    async for message in self.__stream():
  File "/lib/python3.12/site-packages/edge_tts/communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/asyncio/events.py", line 299, in getaddrinfo
    raise NotImplementedError
NotImplementedError
```

**Comment by rany2** [comment]
pyodide issue, I can't do much about it.
