### ISSUE TITLE
Reported a mistake: aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status'

### ISSUE THREAD

**Issue by bingal** [rany2/edge-tts#293]
Traceback (most recent call last):
  File "/Users/ben/opt/anaconda3/envs/py311/bin/edge-tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/edge_tts/util.py", line 120, in main
    asyncio.get_event_loop().run_until_complete(_async_main())
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/edge_tts/util.py", line 115, in _async_main
    await _run_tts(args)
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/edge_tts/util.py", line 50, in _run_tts
    async for chunk in tts.stream():
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/edge_tts/communicate.py", line 305, in stream
    async with aiohttp.ClientSession(
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=dee539c2de704df0b3774596acdd678b'

**Comment by femis** [comment]
+1

**Comment by luomo-pro** [comment]
@rany2
Hello, I've found that this issue only exists in mainland China.
Additionally, Edge browser works fine.
After analyzing network traffic, I discovered that Edge browser's requests include two additional parameters: "Sec-MS-GEC" and "Sec-MS-GEC-Version". For example:
wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&Sec-MS-GEC=C14242292B2241ECB17DD93BD17E481FADED759D70DCE83CA526064D9E90420C&Sec-MS-GEC-Version=1-114.0.1823.67
The key parameter here is "Sec-MS-GEC", which is different each time and has a very short validity period - it expires after a short while.
If we can figure out how "Sec-MS-GEC" is generated, we'll be able to successfully make the calls!

**Comment by KillingFishBall** [comment]
I have updated it to version 6.1.15, but I am still experiencing errors
  File "F:\webview_http_video_maker\src\backend\app\services\voice.py", line 39, in tts
    sub_maker = await _do()
  File "F:\webview_http_video_maker\src\backend\app\services\voice.py", line 32, in _do
    async for chunk in communicate.stream():
  File "D:\Pycharm\miniconda\envs\vir\lib\site-packages\edge_tts\communicate.py", line 498, in stream
    async for message in self.__stream():
  File "D:\Pycharm\miniconda\envs\vir\lib\site-packages\edge_tts\communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "D:\Pycharm\miniconda\envs\vir\lib\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "D:\Pycharm\miniconda\envs\vir\lib\site-packages\aiohttp\client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=01bd3775c0914321a55e5739c04ed9db'

**Comment by zgx0122** [comment]
+1  why this is not working

**Comment by zhahoi** [comment]
![微信截图_20241030144202](https://github.com/user-attachments/assets/d1508bcb-8512-4f3d-8730-775a38debbc5)
I also encountered the same question. I could use edge-tts until last week.

**Comment by zgx0122** [comment]
> > @rany2 Hello, I've found that this issue only exists in mainland China. Additionally, Edge browser works fine. After analyzing network traffic, I discovered that Edge browser's requests include two additional parameters: "Sec-MS-GEC" and "Sec-MS-GEC-Version". For example: wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&Sec-MS-GEC=C14242292B2241ECB17DD93BD17E481FADED759D70DCE83CA526064D9E90420C&Sec-MS-GEC-Version=1-114.0.1823.67 The key parameter here is "Sec-MS-GEC", which is different each time and has a very short validity period - it expires after a short while. If we can figure out how "Sec-MS-GEC" is generated, we'll be able to successfully make the calls!
> 
> Indeed, after testing, using an IP address outside mainland China still allows for normal usage.
>请问你解决了吗，我用了翻墙软件还是不行

**Comment by zgx0122** [comment]
@bingal 请问你解决了吗，我用了翻墙软件还是不行

**Comment by bingal** [comment]
> @bingal 请问你解决了吗，我用了翻墙软件还是不行

没，不过测试用境外 ip 是正常的。你确定使用 edge tts 的时候是走了梯子吗？https://d1tools.com/tools/ai-tts/ 我在这里加上梯子用是正常的。

**Comment by zgx0122** [comment]
@bingal 你这个是软件吗，我是命令行运行的

**Comment by kinson08** [comment]
> > @bingal 请问你解决了吗，我用了翻墙软件还是不行
> 
> 没，不过测试用境外 ip 是正常的。你确定使用 edge tts 的时候是走了梯子吗？https://d1tools.com/tools/ai-tts/ 我在这里加上梯子用是正常的。

必须使用clash x的增强模式才能访问，普通模式仍然出现问题。

**Comment by bingal** [comment]
> @bingal 你这个是软件吗，我是命令行运行的

我是做成了网页工具。网页上运行。我猜你命令行可能没有走梯子代理。

**Comment by bingal** [comment]
> > > @bingal 请问你解决了吗，我用了翻墙软件还是不行
> > 
> > 
> > 没，不过测试用境外 ip 是正常的。你确定使用 edge tts 的时候是走了梯子吗？https://d1tools.com/tools/ai-tts/ 我在这里加上梯子用是正常的。
> 
> 必须使用clash x的增强模式才能访问，普通模式仍然出现问题。

命令行推荐使用 proxychains，配好代理设置之后，需要走代理的命令前面加 proxychains就可以。比如 `proxychains edge-tts --text ...`

**Comment by pureloveljc** [comment]
+1

**Comment by rany2** [comment]
Duplicate https://github.com/rany2/edge-tts/issues/290
