### ISSUE TITLE
status code 403 and version is `edge-tts 7.0.0`

### ISSUE THREAD

**Issue by yiwangwuqian** [rany2/edge-tts#344]
edge-tts --text "Hello, world" --write-media hello.mp3                           
Traceback (most recent call last):
  File "/opt/homebrew/bin/edge-tts", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/edge_tts/util.py", line 136, in main
    asyncio.run(amain())
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.10/site-packages/edge_tts/util.py", line 131, in amain
    await _run_tts(args)
  File "/opt/homebrew/lib/python3.10/site-packages/edge_tts/util.py", line 65, in _run_tts
    async for chunk in tts.stream():
  File "/opt/homebrew/lib/python3.10/site-packages/edge_tts/communicate.py", line 506, in stream
    async for message in self.__stream():
  File "/opt/homebrew/lib/python3.10/site-packages/edge_tts/communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=396b5f2c1cec46d190b8179a01a90948'

**Comment by rany2** [comment]
Can't reproduce on a US and China IP. I think it was just general server unavailability.
