### ISSUE TITLE
I didn't use it too much, but get the warning, “.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:default ”

### ISSUE THREAD

**Issue by bk111** [rany2/edge-tts#77]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Python310\lib\asyncio\base_events.py", line 1097, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Python310\lib\asyncio\base_events.py", line 1127, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
    async with aiohttp.ClientSession(
  File "C:\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Python310\lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
  File "C:\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Python310\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Python310\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Python310\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:default [None]

**Comment by rany2** [comment]
Seems like a connection issue, could you load https://speech.platform.bing.com/ in your browser?

**Comment by bk111** [comment]
load https://speech.platform.bing.com/ on Chrome/Edge:
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0ccJJZAAAAADvR9/e0roiTYU1zKb8cKJEUEFPRURHRTA2MDYARWRnZQ==

**Comment by rany2** [comment]
Seems it's loading fine, I think this is expected. Some users had issues a few days ago which seemed to be caused by an outage and not an effort to ban.

**Comment by dpengchen** [comment]
hi bro,Did you solve it?
