### ISSUE TITLE
An error occurred while running the following command ‘edge-tts --text "hello world" --write-media hello.mp3’

### ISSUE THREAD

**Issue by zhxcorner** [rany2/edge-tts#88]
Running on ubuntu, I encountered the following error but could not resolve it

Traceback (most recent call last):
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/base_events.py", line 1042, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/base_events.py", line 1072, in _create_connection_transport
    await waiter
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/futures.py", line 257, in __await__
    yield self  # This tells Task to wait for completion.
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/futures.py", line 175, in result
    raise self._exception
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/root/miniconda3/envs/eduCA/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/base_events.py", line 1017, in create_connection
    raise exceptions[0]
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/base_events.py", line 1002, in create_connection
    sock = await self._connect_sock(
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/base_events.py", line 916, in _connect_sock
    await self.sock_connect(sock, address)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/selector_events.py", line 485, in sock_connect
    return await fut
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/futures.py", line 260, in __await__
    return self.result()  # May raise too.
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/futures.py", line 175, in result
    raise self._exception
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/selector_events.py", line 490, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/educationalCA/http_api.py", line 63, in Text2Audio
    loop.run_until_complete(func(TEXT,voice_set,OUTPUT_FILE))
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/futures.py", line 175, in result
    raise self._exception
  File "/root/miniconda3/envs/eduCA/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/root/educationalCA/http_api.py", line 26, in func
    await communicate.save(OUTPUT_FILE)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/edge_tts/communicate.py", line 459, in save
    async for message in self.stream():
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/edge_tts/communicate.py", line 305, in stream
    async with aiohttp.ClientSession(
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/miniconda3/envs/eduCA/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:default [Network is unreachable]

**Comment by rany2** [comment]
Seems like the same issue as https://github.com/rany2/edge-tts/issues/85. I wonder if there is some kind of downtime right now impacting IPv6 in certain regions.

**Comment by zhxcorner** [comment]
Thanks for your reply, the problem was solved by reconfiguring the Anaconda virtual environment

**Comment by dpengchen** [comment]
> How was it solved?

**Comment by lonngxiang** [comment]
> Thanks for your reply, the problem was solved by reconfiguring the Anaconda virtual environment

how it fixed？
