### ISSUE TITLE
edge-playback report an error

### ISSUE THREAD

**Issue by photkey** [rany2/edge-tts#9]
```
PS D:\DevScript> edge-playback --text "Hello, world!"

Media file: C:\Users\tuike\AppData\Local\Temp\tmp1eek28_q
Subtitle file: C:\Users\tuike\AppData\Local\Temp\tmpqdfqxmhz

Traceback (most recent call last):
  File "d:\develop\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\develop\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Develop\Python\Python38\Scripts\edge-tts.exe\__main__.py", line 7, in <module>
  File "d:\develop\python\python38\lib\site-packages\edge_tts\util.py", line 156, in main
    asyncio.get_event_loop().run_until_complete(_main())
  File "d:\develop\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "d:\develop\python\python38\lib\site-packages\edge_tts\util.py", line 149, in _main
    await _tts(args)
  File "d:\develop\python\python38\lib\site-packages\edge_tts\util.py", line 32, in _tts
    media_file = open(args.write_media, "wb")  # pylint: disable=consider-using-with
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\tuike\\AppData\\Local\\Temp\\tmp1eek28_q'
Failed to recognize file format.

Exiting... (Errors when loading file)
```

**Comment by rany2** [comment]
The latest version should fix this for Windows

**Comment by photkey** [comment]
The latest version can play sound now, and it stays there at the last line after running, Is this expected behavior?If so, it's already possible to turn off this issue.

![image](https://user-images.githubusercontent.com/60434581/158058102-a4aab19e-08af-4898-8ff9-0f87f53d7a7a.png)

**Comment by rany2** [comment]
Yes it is expected behavior. Press `q` to exit.
